apiVersion: apps/v1
kind: Deployment
metadata:
  name: rumor-pod
  namespace: rumor-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rumor
  template:
    metadata:
      labels:
        app: rumor
    spec:
      containers:
        - name: rumor-api
          resources:
            limits:
              cpu: "2000m"
            requests:
              cpu: "1000m"